# Generated by Django 2.2.2 on 2019-06-28 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ris_aet', models.CharField(default='', max_length=200)),
                ('ris_ip', models.CharField(default='', max_length=200)),
                ('ris_port', models.CharField(default='', max_length=200)),
                ('ris_calling', models.CharField(default='', max_length=200)),
                ('pacs_aet', models.CharField(default='', max_length=200)),
                ('pacs_ip', models.CharField(default='', max_length=200)),
                ('pacs_port', models.CharField(default='', max_length=200)),
                ('pacs_calling', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HandledExaminations',
            fields=[
                ('accession_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('address', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('thining_factor', models.FloatField(default=0.0, null=True)),
                ('thining_factor_change_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Config')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='accepted_procedures',
            field=models.ManyToManyField(to='main_page.ProcedureType'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Department')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
