# Generated by Django 2.1.1 on 2019-02-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('hospital', models.CharField(choices=[('RH', 'Rigshospitalet'), ('HH', 'Herlev hospital'), ('FH', 'Frederiksberg hospital'), ('BH', 'Bispebjerg hospital'), ('GL', 'Glostrup')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
