# Generated by Django 2.1.1 on 2019-02-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted_procedures', models.TextField(default='')),
                ('hosp_aet', models.TextField(default='')),
                ('hosp_ip', models.TextField(default='')),
                ('hosp_port', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.CharField(choices=[('RH', 'Rigshospitalet'), ('HH', 'Herlev hospital'), ('FH', 'Frederiksberg hospital'), ('BH', 'Bispebjerg hospital'), ('GL', 'Glostrup hospital')], max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Config'),
        ),
    ]
