# Generated by Django 2.2.2 on 2019-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='short_name',
            field=models.CharField(choices=[('RH', 'Rigshospitalet'), ('HEH', 'Herlev hospital'), ('HI', 'Hillerød hospital'), ('FH', 'Frederiksberg hospital'), ('BH', 'Bispebjerg hospital'), ('GLO', 'Glostrup hospital'), ('HVH', 'Hvidovre hospital')], max_length=8, null=True),
        ),
    ]
