# Generated by Django 2.1.1 on 2019-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190222_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='hosp_aet',
        ),
        migrations.RemoveField(
            model_name='config',
            name='hosp_ip',
        ),
        migrations.RemoveField(
            model_name='config',
            name='hosp_port',
        ),
        migrations.AddField(
            model_name='config',
            name='pacs_aet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='pacs_calling',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='pacs_ip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='pacs_port',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='rigs_aet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='rigs_calling',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='rigs_ip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='config',
            name='rigs_port',
            field=models.TextField(default=''),
        ),
    ]
