# Generated by Django 2.1.1 on 2019-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20190222_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandledExaminations',
            fields=[
                ('rigs_nr', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='accepted_procedures',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='config',
            name='pacs_aet',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='pacs_calling',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='pacs_ip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='pacs_port',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='rigs_aet',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='rigs_calling',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='rigs_ip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='config',
            name='rigs_port',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.CharField(choices=[('RH', 'Rigshospitalet'), ('HEH', 'Herlev hospital'), ('HI', 'Hillerød hospital'), ('FH', 'Frederiksberg hospital'), ('BH', 'Bispebjerg hospital'), ('GLO', 'Glostrup hospital')], max_length=3),
        ),
    ]
