# Generated by Django 2.2.2 on 2019-07-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20190712_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Config'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Hospital'),
        ),
    ]
