# Generated by Django 2.2.2 on 2019-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20190719_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ae_title', models.CharField(default=None, max_length=16, null=True)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=5)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('samba_ip', models.CharField(max_length=20)),
                ('samba_name', models.CharField(max_length=30)),
                ('samba_user', models.CharField(max_length=30)),
                ('samba_pass', models.CharField(max_length=30)),
                ('samba_pc', models.CharField(max_length=30)),
                ('samba_share', models.CharField(max_length=30)),
                ('AE_title', models.CharField(max_length=30)),
            ],
        ),
    ]
