# Generated by Django 2.1.5 on 2019-05-24 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='thining_factor_change_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
